Revert "[SCSI] cnic: fix error: implicit declaration of function ‘__symbol_get’"
This reverts commit f0a330499cf361eb7ae17c80c02580245f690492.

All the commit did was add a second #include of <linux/module.h> which is
the wrong fix.

Signed-off-by: James Bottomley <James.Bottomley@HansenPartnership.com>