Revert "usb: host/sl811-hcd: fix sparse warning"
This reverts commit 917aa1ac1df44b56a3d319223b16c66cfa12fc20.

Commit 917aa1ac1df4 results in the following error when compiling
x86_64:allyesconfig.

sl811_cs.c:(.text+0x1d3cb72): undefined reference to `sl811h_driver'

Fixes: 917aa1ac1df4 ("usb: host/sl811-hcd: fix sparse warning")
Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>