uapi: mqueue.h: add missing linux/types.h include
Commit e35fe82687ef ("uapi: Use __kernel_long_t in struct mq_attr")
changed the types from long to __kernel_long_t, but didn't add a
linux/types.h include.  Code that tries to include this header directly
breaks:

  /usr/include/linux/mqueue.h:26:2: error: unknown type name '__kernel_long_t'
  __kernel_long_t mq_flags; /* message queue flags   */

This also upsets configure tests for this header:

  checking linux/mqueue.h usability... no
  checking linux/mqueue.h presence... yes
  configure: WARNING: linux/mqueue.h: present but cannot be compiled
  configure: WARNING: linux/mqueue.h:     check for missing prerequisite headers?
  configure: WARNING: linux/mqueue.h: see the Autoconf documentation
  configure: WARNING: linux/mqueue.h:     section "Present But Cannot Be Compiled"
  configure: WARNING: linux/mqueue.h: proceeding with the compiler's result
  checking for linux/mqueue.h... no

Link: http://lkml.kernel.org/r/20170119194644.4403-1-vapier@gentoo.org
Signed-off-by: Mike Frysinger <vapier@gentoo.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>