ARM: PXA: fix gpio-pxa.h build errors
A mismerge in 13a3563 (Merge branch 'depends/rmk/gpio' into next/fixes)
causes these build errors:

In file included from arch/arm/mach-pxa/include/mach/gpio.h:30,
                 from arch/arm/include/asm/gpio.h:6,
                 from include/linux/gpio.h:31,
                 from arch/arm/mach-pxa/generic.c:20:
arch/arm/mach-pxa/include/mach/gpio-pxa.h: In function ■__gpio_is_occupied■:
arch/arm/mach-pxa/include/mach/gpio-pxa.h:121: error: invalid operands to binary >> (have ■void *■ and ■unsigned int■)
arch/arm/mach-pxa/include/mach/gpio-pxa.h:122: error: invalid operands to binary & (have ■void *■ and ■int■)
arch/arm/mach-pxa/include/mach/gpio-pxa.h:129: error: invalid operands to binary & (have ■void *■ and ■int■)

So fix them.

Acked-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>