blackfin: bf533-stamp: Remove bogus "||"
arch/blackfin/mach-bf533/boards/stamp.c:545:2: error: operator '||' has no right operand
arch/blackfin/mach-bf533/boards/stamp.c:662:3: error: 'bfin_snd_resources' undeclared here (not in a function)
arch/blackfin/mach-bf533/boards/stamp.c:662:3: error: negative width in bit-field '<anonymous>'
arch/blackfin/mach-bf533/boards/stamp.c:665:21: error: 'bfin_snd_data' undeclared here (not in a function)
make[4]: *** [arch/blackfin/mach-bf533/boards/stamp.o] Error 1

Introduced by commit 322957c011a1b573d4aee8c0feabfec0b3f381c7 ("blackfin:
Remove references to the bf5x_tdm driver"), which removed two config
options, but only one "||".

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: Lars-Peter Clausen <lars@metafoo.de>
Acked-by: Mike Frysinger <vapier@gentoo.org>
Signed-off-by: Mark Brown <broonie@linaro.org>