soc: qcom: event_timer: Adapt to new timerqueue_head struct
Upstream commit 8cf4d696c17a7ba24be26cd55c3ddeb74146e6cc "lib/timerqueue: Rely on rbtree semantics for next timer" reworked this and caused a compilation failure.

./drivers/soc/qcom/event_timer.c:54:3: error: field designator 'head' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
        .head = RB_ROOT,
         ^
./drivers/soc/qcom/event_timer.c:55:3: error: field designator 'next' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
        .next = NULL,
         ^
2 errors generated.

Change-Id: I6cdd2c599ad33357feb4c557f15f3df0f4a34a05
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>