ANDROID: sched: Add over-utilization/tipping point indicator
Energy-aware scheduling is only meant to be active while the system is
_not_ over-utilized. That is, there are spare cycles available to shift
tasks around based on their actual utilization to get a more
energy-efficient task distribution without depriving any tasks. When
above the tipping point task placement is done the traditional way based
on load_avg, spreading the tasks across as many cpus as possible based
on priority scaled load to preserve smp_nice. Below the tipping point we
want to use util_avg instead. We need to define a criteria for when we
make the switch.

The util_avg for each cpu converges towards 100% (1024) regardless of
how many task additional task we may put on it. If we define
over-utilized as:

sum_{cpus}(rq.cfs.avg.util_avg) + margin > sum_{cpus}(rq.capacity)

some individual cpus may be over-utilized running multiple tasks even
when the above condition is false. That should be okay as long as we try
to spread the tasks out to avoid per-cpu over-utilization as much as
possible and if all tasks have the _same_ priority. If the latter isn't
true, we have to consider priority to preserve smp_nice.

For example, we could have n_cpus nice=-10 util_avg=55% tasks and
n_cpus/2 nice=0 util_avg=60% tasks. Balancing based on util_avg we are
likely to end up with nice=-10 tasks sharing cpus and nice=0 tasks
getting their own as we 1.5*n_cpus tasks in total and 55%+55% is less
over-utilized than 55%+60% for those cpus that have to be shared. The
system utilization is only 85% of the system capacity, but we are
breaking smp_nice.

To be sure not to break smp_nice, we have defined over-utilization
conservatively as when any cpu in the system is fully utilized at it's
highest frequency instead:

cpu_rq(any).cfs.avg.util_avg + margin > cpu_rq(any).capacity

IOW, as soon as one cpu is (nearly) 100% utilized, we switch to load_avg
to factor in priority to preserve smp_nice.

With this definition, we can skip periodic load-balance as no cpu has an
always-running task when the system is not over-utilized. All tasks will
be periodic and we can balance them at wake-up. This conservative
condition does however mean that some scenarios that could benefit from
energy-aware decisions even if one cpu is fully utilized would not get
those benefits.

For system where some cpus might have reduced capacity on some cpus
(RT-pressure and/or big.LITTLE), we want periodic load-balance checks as
soon a just a single cpu is fully utilized as it might one of those with
reduced capacity and in that case we want to migrate it.

cc: Ingo Molnar <mingo@redhat.com>
cc: Peter Zijlstra <peterz@infradead.org>
Signed-off-by: Morten Rasmussen <morten.rasmussen@arm.com>
Change-Id: I09caeeb1151b5c02d67ed738e25728d1771eb45f
Signed-off-by: Chris Redpath <chris.redpath@arm.com>
Git-commit: 58f9f0c7360ef60ed493f9454b002fefa33adfee
Git-repo: https://android.googlesource.com/kernel/common/
[satyap@codeaurora.org: fixed below compilation errors for ARCH=um
kernel/sched/fair.c: In function 'enqueue_task_fair':
kernel/sched/fair.c:4928:23: error: 'struct rq' has no member named 'rd'
    if (!task_new && !rq->rd->overutilized &&
                        ^
kernel/sched/fair.c:4929:26: error: 'struct rq' has no member named 'cpu'
       cpu_overutilized(rq->cpu))
                          ^
kernel/sched/fair.c:4930:6: error: 'struct rq' has no member named 'rd'
    rq->rd->overutilized = true;
      ^
kernel/sched/fair.c: In function 'task_tick_fair':
kernel/sched/fair.c:9468:9: error: 'struct rq' has no member named 'rd'
  if (!rq->rd->overutilized && cpu_overutilized(task_cpu(curr)))
         ^
kernel/sched/fair.c:9469:5: error: 'struct rq' has no member named 'rd'
   rq->rd->overutilized = true;
     ^
]
Signed-off-by: Satya Durga Srinivasu Prabhala <satyap@codeaurora.org>