tty/amiserial: Add missing argument for tty_unlock()
commit ca988af4ec7a3586cffa658f0bc4f607dc2d2645 ("tty_lock: Localise the lock")
missed that c897de3c332eb0914eef122d4ae7374334cfa60d ("drivers/tty/amiserial.c:
add missing tty_unlock") just added a new caller of tty_unlock():

drivers/tty/amiserial.c: In function ‘set_serial_info’:
drivers/tty/amiserial.c:1077: error: too few arguments to function ‘tty_unlock’

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>