ANDROID: sched_param: Include uapi/linux/sched/types.h>
Upstream commit 63a35bbf3b81 ("sched/headers: Move various ABI
definitions to <uapi/linux/sched/types.h>") moved struct sched_param
definition to <uapi/linux/sched/types.h>. Hence include that otherwise
we run into related build errors:

  CC [M]  drivers/mmc/core/queue.o
drivers/mmc/core/queue.c: In function ‘mmc_queue_thread’:
drivers/mmc/core/queue.c:50:9: error: variable ‘scheduler_params’ has initializer but incomplete type
  struct sched_param scheduler_params = {0};
         ^
drivers/mmc/core/queue.c:50:41: warning: excess elements in struct initializer struct sched_param scheduler_params = {0};
                                         ^
drivers/mmc/core/queue.c:50:41: note: (near initialization for ‘scheduler_params’)
drivers/mmc/core/queue.c:50:21: error: storage size of ‘scheduler_params’ isn’t known
  struct sched_param scheduler_params = {0};
                     ^

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>