staging: r8188eu: Fix build error with random configuration
The kbuild test robot reports the following error:

tree:   git://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git master
head:   e4a745f9519ef2bbb9d75212ae1cca7582d76266
commit: 17f3f3637e510e9c1115df521a665b11685362c2 [7011/7939] staging: r8188eu: Turn on build of new driver
config: x86_64-randconfig-x0-0828 (attached as .config)

All error/warnings:

   drivers/staging/rtl8188eu/core/rtw_p2p.c: In function 'go_add_group_info_attr':
>> drivers/staging/rtl8188eu/core/rtw_p2p.c:70:11: error: 'struct sta_info' has no member named 'is_p2p_device'
      if (psta->is_p2p_device) {

This and the following errors were caused by an incorrect nesting of
conditional compilation directives.

Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>