soc: brcmstb: select SOC_BUS
The newly added code for the SoC bus fails to link if the
bus is not built:

drivers/soc/built-in.o: In function `brcmstb_soc_device_init':
:(.init.text+0x110): undefined reference to `soc_device_register'

This adds a 'select' statement to avoid the error.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: c13e5646e148 ("soc: brcmstb: add SoC driver to brcmstb")
Acked-by: Florian Fainelli <f.fainelli@gmail.com>