Revert "[media] siano: apply debug flag to module level"
This reverts commit 50cd3184b94acd6b5f3ac64f3b87b038d70ed594.

As reported by Stephen Rothwell:

After merging the v4l-dvb tree, today's linux-next build (x86_64
allmodconfig) failed like this:

ERROR: "sms_dbg" [drivers/media/dvb/siano/smsusb.ko] undefined!
ERROR: "sms_dbg" [drivers/media/dvb/siano/smsdvb.ko] undefined!

Caused by commit 50cd3184b94a ("[media] siano: apply debug flag to module
level").

Relevant config:
CONFIG_SMS_SIANO_MDTV=m
CONFIG_SMS_USB_DRV=m
CONFIG_SMS_SDIO_DRV=m

Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>