Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
This reverts commit 97268ebaac9441d5a4d3afe7bbbe901ee2f3cd82, which
causes a build failure:

drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer
Signed-off-by: Hafidz Muzakky <ais.muzakky@gmail.com>