tracing, net: fix net tree and tracing tree merge interaction
Today's linux-next build (powerpc ppc64_defconfig) failed like this:

 In file included from net/core/skbuff.c:69:
 include/trace/skb.h:4: error: expected ')' before '(' token
 include/trace/skb.h:4: error: expected ')' before '(' token
 [...]

Caused by commit f8993afd7290571957f8635fb200e2040e2de018 ("tracing:
replace TP<var> with TP_<var>") from the tracing tree interacting with
commit 6360e5fa4b524287c9d9929021fc7deee0d45f3c ("Network Drop Monitor:
Add trace declaration for skb frees") from the net tree.

Acked-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Ingo Molnar <mingo@elte.hu>